### ISSUE TITLE
Some partial crawls end up running very long and its unclear why they do

### ISSUE THREAD

**Issue by TimDaub** [neume-network/data#42]
- example https://github.com/neume-network/data/actions/runs/3009785822
- here's one where we see an error and it's a range error that may have to do with the strategy lifecycle: https://github.com/neume-network/data/runs/8231331123?check_suite_focus=true#step:10:36

**Comment by il3ven** [comment]
This issue seems to be because of incorrect arguments to call-block-logs. From the logs we can see that call-block-logs was called for block range [`[ 15491637, 0 ]`](https://github.com/neume-network/data/runs/8234616425?check_suite_focus=true#step:10:31). This caused an error inside call-block-logs. That error bubbled up and caused an [`UnhandledPromiseRejectionWarning `](https://github.com/neume-network/data/runs/8234616425?check_suite_focus=true#step:10:36). The `extract` promise never resolved or rejected properly.

The proper rejection in case of unhandled errors has been addressed in neume-network/strategies#272. There are still two issues left:
- lastBlockNumber returns 0
- call-block-logs doesn't check the arguments properly

**Comment by TimDaub** [comment]
> From the logs we can see that call-block-logs was called for block range [`[ 15491637, 0 ]`](https://github.com/neume-network/data/runs/8234616425?check_suite_focus=true#step:10:31).

Great find!

> That error bubbled up and caused an [`UnhandledPromiseRejectionWarning `](https://github.com/neume-network/data/runs/8234616425?check_suite_focus=true#step:10:36).

IMO what should have happened is that the entire program should have crashed completely. Or what do you think?

**Comment by TimDaub** [comment]
> * lastBlockNumber returns 0

I think you mean https://github.com/neume-network/data/blob/e7b840e17e578ea6ed36d404c0375cf238532918/scripts/generateBlockLogsCrawlPath#L5

**Comment by il3ven** [comment]
> IMO what should have happened is that the entire program should have crashed completely. I think for anything unexpected we want to crash and then we'll add an issue and build the newly emerged error path. Or what do you think?

I agree and that's what this PR does: https://github.com/neume-network/core/pull/85

> I think you mean

Yes, yes. The `blockNumber` script is returning 0.

**Comment by TimDaub** [comment]
> The `blockNumber` script is returning 0.

yeah as you already mentioned, I agree that the following are the problems to solve:



> * blockNumber returns 0 (and it shouldn't)
> 
> * call-block-logs doesn't check the arguments properly (and it should - and crash if it receives end = 0)
